name: F1 Tracker

on:
  schedule:
    - cron: "*/1 * * * *"
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tracker
        run: python tracker.py
      - name: Commit status file
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add status.json
          git commit -m "Update status" || echo "No changes"
          git push
